# .golangci.yml
run:
  timeout: 5m
  issues-exit-code: 1
  go: '1.23'



linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - gocritic
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable:
      - shadow
      - unreachable
  unused:
    exported-fields-are-used: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3
  exclude-dirs:
    - vendor
    - .git
  uniq-by-line: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true